---
apiVersion: wego.weave.works/v1alpha1
kind: Application
metadata:
  labels:
    wego.weave.works/app-identifier: wego-89b2ca5e4acfe47760fa148b445f9a49
  name: podinfo-deploy
  namespace: wego-system
spec:
  branch: main
  config_url: ssh://git@github.com/pabeli/gitops-config.git
  deployment_type: kustomize
  path: ./
  source_type: git
  url: ssh://git@github.com/pabeli/podinfo-deploy.git
